-- Generated by `python -m app.tools.dump_schema`.  Do not edit by hand:
-- change app/models.py and regenerate, so schema and code cannot drift.

BEGIN;

CREATE TABLE api_calls (
	id SERIAL NOT NULL, 
	service VARCHAR(32) NOT NULL, 
	direction VARCHAR(8) NOT NULL, 
	method VARCHAR(8) NOT NULL, 
	url VARCHAR(1024) NOT NULL, 
	attempt INTEGER NOT NULL, 
	status_code INTEGER, 
	duration_ms INTEGER, 
	request_body TEXT, 
	response_body TEXT, 
	error TEXT, 
	correlation_id VARCHAR(64), 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id)
);
CREATE INDEX ix_api_calls_correlation ON api_calls (correlation_id);
CREATE INDEX ix_api_calls_service_time ON api_calls (service, created_at);

CREATE TABLE fx_rates (
	id SERIAL NOT NULL, 
	base VARCHAR(3) NOT NULL, 
	quote VARCHAR(3) NOT NULL, 
	rate NUMERIC(18, 8) NOT NULL, 
	source VARCHAR(64) NOT NULL, 
	fetched_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id)
);
CREATE INDEX ix_fx_pair_time ON fx_rates (base, quote, fetched_at);

CREATE TABLE idempotency_keys (
	id SERIAL NOT NULL, 
	scope VARCHAR(64) NOT NULL, 
	key VARCHAR(128) NOT NULL, 
	request_hash VARCHAR(64) NOT NULL, 
	state VARCHAR(16) NOT NULL, 
	response JSON, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	completed_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_idempotency_scope_key UNIQUE (scope, key)
);

CREATE TABLE price_change_log (
	id SERIAL NOT NULL, 
	store_code VARCHAR(32) NOT NULL, 
	product_ext_id VARCHAR(32) NOT NULL, 
	offer_ext_id VARCHAR(64), 
	old_price NUMERIC(12, 4), 
	new_price NUMERIC(12, 4) NOT NULL, 
	changed_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id)
);
CREATE INDEX ix_price_change_product_time ON price_change_log (store_code, product_ext_id, changed_at);

CREATE TABLE store_orders (
	id SERIAL NOT NULL, 
	store_code VARCHAR(32) NOT NULL, 
	order_ext_id VARCHAR(128) NOT NULL, 
	reservation_ext_id VARCHAR(128), 
	state VARCHAR(16) NOT NULL, 
	source VARCHAR(16) NOT NULL, 
	raw JSON NOT NULL, 
	received_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	delivered_at TIMESTAMP WITH TIME ZONE, 
	last_error TEXT, 
	attempts INTEGER NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_store_order_identity UNIQUE (store_code, order_ext_id)
);
CREATE INDEX ix_store_orders_state ON store_orders (state);

CREATE TABLE store_products (
	id SERIAL NOT NULL, 
	store_code VARCHAR(32) NOT NULL, 
	product_ext_id VARCHAR(32) NOT NULL, 
	name VARCHAR(512) NOT NULL, 
	name_normalized VARCHAR(512) NOT NULL, 
	match_key VARCHAR(600) NOT NULL, 
	slug VARCHAR(512), 
	product_type VARCHAR(64), 
	region VARCHAR(64), 
	platform VARCHAR(64), 
	qty INTEGER NOT NULL, 
	min_price NUMERIC(12, 4), 
	retail_min_price NUMERIC(12, 4), 
	available_to_buy BOOLEAN NOT NULL, 
	price_limit_min NUMERIC(12, 4), 
	price_limit_max NUMERIC(12, 4), 
	remote_updated_at TIMESTAMP WITH TIME ZONE, 
	raw JSON NOT NULL, 
	synced_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_store_product_identity UNIQUE (store_code, product_ext_id)
);
CREATE INDEX ix_store_products_match_key ON store_products (store_code, match_key);
CREATE INDEX ix_store_products_name_norm ON store_products (name_normalized);

CREATE TABLE suppliers (
	id SERIAL NOT NULL, 
	code VARCHAR(32) NOT NULL, 
	name VARCHAR(128) NOT NULL, 
	enabled BOOLEAN NOT NULL, 
	settings JSON NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (code)
);

CREATE TABLE sync_runs (
	id SERIAL NOT NULL, 
	kind VARCHAR(32) NOT NULL, 
	state VARCHAR(16) NOT NULL, 
	stats JSON NOT NULL, 
	error TEXT, 
	started_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	finished_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
);
CREATE INDEX ix_sync_runs_kind_started ON sync_runs (kind, started_at);

CREATE TABLE supplier_products (
	id SERIAL NOT NULL, 
	supplier_id INTEGER NOT NULL, 
	kind VARCHAR(16) NOT NULL, 
	category_ext_id VARCHAR(128) NOT NULL, 
	offer_ext_id VARCHAR(128) NOT NULL, 
	category_name VARCHAR(512), 
	name VARCHAR(512) NOT NULL, 
	name_normalized VARCHAR(512) NOT NULL, 
	region VARCHAR(64), 
	platform VARCHAR(64), 
	region_restricted BOOLEAN NOT NULL, 
	price_supplier NUMERIC(12, 4) NOT NULL, 
	supplier_currency VARCHAR(3) NOT NULL, 
	stock INTEGER NOT NULL, 
	min_order_quantity INTEGER NOT NULL, 
	max_order_quantity INTEGER NOT NULL, 
	content_hash VARCHAR(64) NOT NULL, 
	raw JSON NOT NULL, 
	is_active BOOLEAN NOT NULL, 
	missing_runs INTEGER NOT NULL, 
	first_seen_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	last_seen_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_supplier_product_identity UNIQUE (supplier_id, kind, category_ext_id, offer_ext_id), 
	CONSTRAINT ck_supplier_product_stock_non_negative CHECK (stock >= 0), 
	FOREIGN KEY(supplier_id) REFERENCES suppliers (id) ON DELETE CASCADE
);
CREATE INDEX ix_supplier_products_active ON supplier_products (supplier_id, is_active);
CREATE INDEX ix_supplier_products_name_norm ON supplier_products (name_normalized);

CREATE TABLE product_mappings (
	id SERIAL NOT NULL, 
	supplier_product_id INTEGER NOT NULL, 
	store_code VARCHAR(32) NOT NULL, 
	store_product_id INTEGER, 
	status VARCHAR(16) NOT NULL, 
	score FLOAT, 
	method VARCHAR(32), 
	candidates JSON NOT NULL, 
	markup_percent_override FLOAT, 
	fixed_price_override NUMERIC(12, 4), 
	sync_enabled BOOLEAN NOT NULL, 
	reviewed_by VARCHAR(128), 
	reviewed_at TIMESTAMP WITH TIME ZONE, 
	note TEXT, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_mapping_supplier_product UNIQUE (supplier_product_id), 
	CONSTRAINT uq_mapping_store_product UNIQUE (store_code, store_product_id), 
	FOREIGN KEY(supplier_product_id) REFERENCES supplier_products (id) ON DELETE CASCADE, 
	FOREIGN KEY(store_product_id) REFERENCES store_products (id) ON DELETE SET NULL
);
CREATE INDEX ix_mappings_status ON product_mappings (status);

CREATE TABLE order_items (
	id SERIAL NOT NULL, 
	order_id INTEGER NOT NULL, 
	line_ref VARCHAR(128) NOT NULL, 
	mapping_id INTEGER, 
	product_ext_id VARCHAR(32), 
	quantity INTEGER NOT NULL, 
	state VARCHAR(16) NOT NULL, 
	purchase_idempotency_key VARCHAR(128), 
	supplier_order_ext_id VARCHAR(128), 
	supplier_cost NUMERIC(12, 4), 
	keys_count INTEGER NOT NULL, 
	delivered_at TIMESTAMP WITH TIME ZONE, 
	last_error TEXT, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_order_item_line UNIQUE (order_id, line_ref), 
	FOREIGN KEY(order_id) REFERENCES store_orders (id) ON DELETE CASCADE, 
	FOREIGN KEY(mapping_id) REFERENCES product_mappings (id) ON DELETE SET NULL
);
CREATE INDEX ix_order_items_state ON order_items (state);

CREATE TABLE store_offers (
	id SERIAL NOT NULL, 
	mapping_id INTEGER NOT NULL, 
	store_code VARCHAR(32) NOT NULL, 
	offer_ext_id VARCHAR(64), 
	product_ext_id VARCHAR(32) NOT NULL, 
	state VARCHAR(16) NOT NULL, 
	active BOOLEAN NOT NULL, 
	pushed_price NUMERIC(12, 4), 
	pushed_inventory INTEGER, 
	pushed_active BOOLEAN, 
	last_pushed_at TIMESTAMP WITH TIME ZONE, 
	pending_job_id VARCHAR(64), 
	last_error TEXT, 
	consecutive_failures INTEGER NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_offer_mapping UNIQUE (mapping_id), 
	CONSTRAINT uq_offer_ext_id UNIQUE (store_code, offer_ext_id), 
	FOREIGN KEY(mapping_id) REFERENCES product_mappings (id) ON DELETE CASCADE
);
CREATE INDEX ix_offers_state ON store_offers (state);

CREATE TABLE delivered_keys (
	id SERIAL NOT NULL, 
	order_item_id INTEGER NOT NULL, 
	code_encrypted TEXT NOT NULL, 
	fingerprint VARCHAR(64) NOT NULL, 
	kind VARCHAR(16) NOT NULL, 
	delivered_to_store BOOLEAN NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_delivered_key_fingerprint UNIQUE (fingerprint), 
	FOREIGN KEY(order_item_id) REFERENCES order_items (id) ON DELETE CASCADE
);

COMMIT;
