"""Generate migrations/001_initial.sql from the SQLAlchemy models.

    python -m app.tools.dump_schema > migrations/001_initial.sql

Running this after a model change keeps the committed SQL and the models in
step, so the migration file is never a hand-written guess at what the code
expects.
"""

from __future__ import annotations

import sys

from sqlalchemy.schema import CreateIndex, CreateTable

from app.models import Base


def render(dialect_name: str = "postgresql") -> str:
    if dialect_name == "postgresql":
        from sqlalchemy.dialects.postgresql import dialect as make_dialect
    else:  # pragma: no cover - convenience only
        from sqlalchemy.dialects.sqlite import dialect as make_dialect

    dialect = make_dialect()
    lines = [
        "-- Generated by `python -m app.tools.dump_schema`.  Do not edit by hand:",
        "-- change app/models.py and regenerate, so schema and code cannot drift.",
        "",
        "BEGIN;",
        "",
    ]
    for table in Base.metadata.sorted_tables:
        lines.append(str(CreateTable(table).compile(dialect=dialect)).strip() + ";")
        for index in sorted(table.indexes, key=lambda i: i.name or ""):
            lines.append(str(CreateIndex(index).compile(dialect=dialect)).strip() + ";")
        lines.append("")
    lines.append("COMMIT;")
    return "\n".join(lines)


if __name__ == "__main__":
    target = sys.argv[1] if len(sys.argv) > 1 else "postgresql"
    sys.stdout.write(render(target) + "\n")
